Homework4.1
hexekutor/homework pull request #8
Opened 2018-11-25 17:03 UTC by hexekutor

fixed homework3 and homework4

2018-11-26 08:20 UTC, saint88 requested changes
Нужно исправить все замечания и отправить пул реквест по новой с изменениями

2018-11-26 08:20 UTC, saint88 commented on homework3/arraySort/pom.xml
> +            <build>
Не нужно хранить плагины в профилях

2018-11-26 08:20 UTC, saint88 commented on homework3/arraySort/pom.xml
> +            <build>
Аналогично как выше

2018-11-26 08:20 UTC, saint88 commented on homework3/arraySort/pom.xml
> +            <build>
Аналогично как выше

2018-11-26 08:20 UTC, saint88 commented on homework3/prime_numbers/pom.xml
> +            <build>
не нужно хранить плагин в профиле

2018-11-26 08:20 UTC, saint88 commented on homework3/prime_numbers/pom.xml
> +            <build>
не нужно хранить плагин в профиле

2018-11-26 08:20 UTC, saint88 commented on homework3/prime_numbers/pom.xml
> +            <build>
не нужно хранить плагин в профиле

2018-11-26 08:20 UTC, saint88 commented on homework3/studentMicroservice/pom.xml
> +            <plugin>
не нужно хранить плагин в профиле

2018-11-26 08:20 UTC, saint88 commented on homework3/studentMicroservice/pom.xml
> +            <build>
аналогично как выше

2018-11-26 08:20 UTC, saint88 commented on homework3/studentMicroservice/pom.xml
> +                    <plugin>
аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework3/studentMicroservice/pom.xml
> +            <build>
аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/pom.xml
> +            <build>
Аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/pom.xml
> +            <build>
Аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/pom.xml
> +                    <plugin>
Аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/GooglePageMainPage.java
> +    public void resultBarShouldExist(){
Ты когда проверяешь, что у тебя result bar существует на странице, то ты же остаешься на текущей странице, поэтому метод должен возвращать GooglePageMainPage

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/GooglePageMainPage.java
> +    public GooglePageMainPage open(String ... args) {
А зачем тебе этот метод open?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +                @Url(name = "namesecret", url = "/%1"),
А зачем ты тут так открываешь страницу? Ведь лучше открывать через аннотацию DefaultUrl("/namesecret")

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private List<WebElement> letterButtonLocator;
Это не локатор, а уже элемент, поэтому тут писать Locator в имени не нужно

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private WebElement inputFieldLocator;
Писать Locator в имени не нужно, так как это уже элемент

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/GooglePageMainPage.java
> +    private WebElement searchInputFieldLocator;
Писать в имени Locator не нужно, так как это не локатор, а элемент

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/GooglePageMainPage.java
> +    private WebElement resultStatsLocator;
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/GooglePageMainPage.java
> +    private WebElement resultBarLocator;
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private WebElement suggestMenuLocator;
Аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private WebElement sexTypeslocator;
Аналогично выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String suggestElementSelector = "//div[@class ='suggest__item js-suggest__item']";
css -> Selector, xpath -> Locator

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String searchButtonSelector = "//button[@class ='button button_nowrap button_color_project']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String searchResultsSelector = "//div[@class ='newsitem newsitem_vertical newsitem_special newsitem_border_bottom']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String searchSecondResultSelector = "//div[@class ='article__item article__item_alignment_left article__item_html']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String selectButtonSelector = "//div[@class ='dropdown dropdown_scrollable dropdown_scrollable dropdown_scrollable js-select js-module']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String selectMenuSelector = "//div[@class ='suggest__inner js-select__options__list js-scrollable__view dropdown__scroll']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    private String womanSelectElementSelector = "//div[@class ='suggest__item js-select__options__item' and text()='Женские']";
Выше

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    public MailNameSecretPage open(String ... args) {
А зачем тебе на странице несколько методов open?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +        for(WebElement letterButton : letterButtonLocator){
Вот эту логику красиво можно сделать через stream + filter

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +            if(Objects.equals(letterButton.findElement(By.cssSelector("[class='filter__text']")).getText(), "А")){
А почему ты этот селектор не вынес наверх к остальным селекторам?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    public void checkLetterButton(){
А для другой буквы будем писать отдельный метод?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +    public void checkLetterButton(){
И почему после проверки ты возвращаешь void? Ты же остаешься на текущей странице и никуда не переходишь?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +        driver.findElement(By.xpath(womanSelectElementSelector)).click();
Выше же через Select делал правильно, надо было немного доделать, а тут сделал почему-то без класса Select и следовательно неправильно

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailPetsPage.java
> +    private WebElement newsFieldLocator;
newsField

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailPetsPage.java
> +    public MailPetsPage open(String ... args) {
Зачем тебе 2 метода open?

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/MailPetsPage.java
> +    private List<WebElement> countNews(){
Из названия метода я лично понял, что ты возвращаешь количество новостей? а по реализации зачем-то ты возвращаешь список элементов этих новостей. Может имеет смысл возвращать список заголовков этих новостей, а не список элементов

2018-11-26 08:20 UTC, saint88 commented on homework4/src/main/java/mfti/pages/Page.java
> +public class Page<T> {
Это абстрактный класс

2018-11-26 08:20 UTC, saint88 commented on homework4/src/test/java/CheckResultsOfSearch_Test.java
> +
Что это за пустое место для рекламы? Убери пустые строки из теста

2018-11-26 08:20 UTC, saint88 commented on homework4/src/test/java/MailNameSecret_test.java
> +                .pressLetterButton()
А если будет другая буква в данных теста, что будем делать? Менять в методе?

2018-11-26 13:08 UTC, hexekutor commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +        driver.findElement(By.xpath(womanSelectElementSelector)).click();
ну он не работает, не знаю почему

2018-11-26 13:13 UTC, hexekutor commented on homework4/src/main/java/mfti/pages/MailNameSecretPage.java
> +                @Url(name = "namesecret", url = "/%1"),
чтоб показать что штука, которую задали написать работает

2018-11-27 06:08 UTC, saint88 approved these changes
Вот теперь отлично. Молодец. За 3 дз ставлю в ведомость 10 баллов и за 4 дз тоже ставлю в ведомость 10 баллов. Молодец.

2018-11-27 06:08 UTC, merged