homework5-6
hexekutor/homework pull request #9
Opened 2018-12-11 15:12 UTC by hexekutor

2018-12-12 11:20 UTC, saint88 requested changes
Что нужно сделать:
1. Поправить все замечания и исправить локаторы. Не нужно просто копировать классы элементов. Нужно искать уникальные классы и элементы. Локатор должен быть не чувствителен к порядку значений в атрибуте
2. ОЧЕНЬ ВАЖНО: убрать весь мусор с проекта. Я уже делал такое замечание, что не нужно пушить все подряд. Зачем в репозитории твои конфиги IDEA, скомпилированные классы и результаты прогонов в JSON. Все лишнее надо убрать.

2018-12-12 11:20 UTC, saint88 commented on homework5/carsProject/src/main/java/mfti/pages/CarsPage.java
> +    @FindBy(css = "[class='link link_underline link_icon color_black']")
Это плохой локатор, так как порядок следования классов может поменяться

2018-12-12 11:20 UTC, saint88 commented on homework5/carsProject/src/main/java/mfti/pages/CarsPage.java
> +    @FindBy(css = "[class='overlay__content js-popup_blocks']")
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework5/carsProject/src/main/java/mfti/pages/CarsPage.java
> +    @FindBy(css = "[class='text text_bold_large']")
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework5/carsProject/src/main/java/mfti/pages/CarsPage.java
> +    @FindBy(css = "[class='icon icon_close js-popup_close popup__close']")
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework5/carsProject/src/main/java/mfti/pages/CarsPage.java
> +        assertTrue("закрытие попапа", standartWaiter.waitForCondition(
Лучше сделать клик и проверку, что попап не отображается 2 разными методами, так как если у тебя будет клик например по кнопке отмена, то прийдется дублировать код проверки того, что попап не отображается

2018-12-12 11:20 UTC, saint88 commented on homework5/petsProject/src/main/java/pages/PetsArticlePage.java
> +    @FindBy(css = "[class='note__text breadcrumbs__text js-ago']")
Это плохой локатор, так как порядок классов может измениться

2018-12-12 11:20 UTC, saint88 commented on homework5/petsProject/src/main/java/pages/PetsArticlePage.java
> +        assertTrue("проверка правильности даты", dateString.matches("\\d+ [а-я]+ \\d+"));
Лучше пробелы проверять через \s или \s+ в регулярке.

2018-12-12 11:20 UTC, saint88 commented on homework5/sportProject/src/main/java/mfti/pages/SportPage.java
> +@DefaultUrl("/news/football-worldcup/32246552/")
А если будет другой id? Его нужно передавать через параметр и хранить в enum

2018-12-12 11:20 UTC, saint88 commented on homework5/sportProject/src/test/java/Sport_Test.java
> +        new SportPage(driver)
А где проверка наличия слотов в запросе? Тебе нужно получить логи и проверить, что в трафике есть запросы на указанные в кейсе слоты и передача их параметров

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/month/Month.java
> +    private static final String[] months = {"Январь", "Февраль", "Март", "Апрель",
Зачем так делать? Есть же LocalDate

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherArticlePage.java
> +    @FindBy(css = "[class='note__text breadcrumbs__text js-ago']")
Такой локатор не пойдет. Классы могут менять свой порядок

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +    @FindBy(css = "[class='calendar__month js-calendar_month']")
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +    @FindBy(css = "[class='icon icon_less js-calendar_prev']")
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +    @FindBy(css = "[class='calendar__control calendar__control_next']")
Аналогично выше. И обрати внимание, что у тебя точно такой же локатор написан выше, но откливается он только названием кнопочки. Поэтому лучше создать enum NavigationData. Там хранить кнопочки и передавать их в локатор.

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +    public WeatherCalendarPage pressNextCalendarButton(){
Такой метод написан выше. Сделать для этих кнопочек надо один общий метод

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +        assertTrue("Месяц изменился", standartWaiter.
Не нужно мешать клик по кнопке и проверки. Вынести все асерты надо в отдельные методы. Ты можешь сделать паттерн action, но это будет отдельный метод в котором будут просто вызываться методы-шаги

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherCalendarPage.java
> +        assertTrue("переход на другую страницу", standartWaiter.
Аналогично не нужно мешать клик и проверки

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +    @FindBy(css = "[class='js-input pm-toolbar__search__input  pm-toolbar__search__input_not-expandable pm-toolbar__search__input_not-adaptive']")
такой css не пойдет. Причина написана выше

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +    @FindBy(css = "[class='icon__inner icon__inner_add']")
Переписать

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +    @FindBy(css = "[class='js-text-inner pm-toolbar__button__text__inner  pm-toolbar__button__text__inner_noicon pm-toolbar__button__text__inner_dropdown']")
css не пойдет

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +    private String cityHeaderSelector = "[class='js-text-inner pm-toolbar__button__text__inner  pm-toolbar__button__text__inner_noicon pm-toolbar__button__text__inner_dropdown']";
не пойдет

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +        assertTrue("Города в избранном видны", standartWaiter.
смешал кучу степов в одном. Нужно все проверки вынести в отдельные методы, а если хочешь action, то в методе надо просто их вызвать

2018-12-12 11:20 UTC, saint88 commented on homework5/weatherProject/src/main/java/mfti/pages/WeatherPage.java
> +        Actions actions = new Actions(driver);
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework6/otvetMailProject/src/main/java/pages/MainPage.java
> +    private SelenideElement openedPage = $("[class='f_left t80'] b");
Порядок классов может поменяться. И ты уверен, что это и есть уникальные классы?

2018-12-12 11:20 UTC, saint88 commented on homework6/otvetMailProject/src/main/java/pages/MainPage.java
> +    private ElementsCollection avatarCollection = $$("[class='q--li--ava small-avatar']");
Аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework6/otvetMailProject/src/main/java/pages/MainPage.java
> +    private int getCodeHttpRequest() {
Этот метод для всех страниц одинаковый, поэтому его надо вынести в PageObject

2018-12-12 11:20 UTC, saint88 commented on homework6/paginationProject/src/main/java/pages/MainPage.java
> +@DefaultUrl("/Rating/All/Today/Visitors/")
All, Today и Visitors должны передаваться через параметры в URL и храниться в виде enum

2018-12-12 11:20 UTC, saint88 commented on homework6/paginationProject/src/main/java/pages/MainPage.java
> +    private SelenideElement openedPage = $("[class='f_left t80'] b");
Это плохой локатор, причина написана выше

2018-12-12 11:20 UTC, saint88 commented on homework6/paginationProject/src/main/java/pages/MainPage.java
> +    private ElementsCollection navigationLinks = $$("[class='f_left t80'] a");
Аналогично

2018-12-12 11:20 UTC, saint88 commented on homework6/paginationProject/src/main/java/pages/MainPage.java
> +    public MainPage goNextTenPages(){
А зачем тут проверять переход на 10 страниц?

2018-12-12 11:20 UTC, saint88 commented on homework6/paginationProject/src/main/java/pages/MainPage.java
> +    public MainPage goBackTenPages(){
А зачем тут проверять переход назад на 10 и этот метод очень похожий на метод внизу. Надо сделать, если хочешь все же проверять десятки, один общий метод

2018-12-12 11:20 UTC, saint88 commented on homework6/tvProgramProject/src/main/java/pages/MainPage.java
> +            "[class='input-group js-module'] button");
Этот локатор плохой и его надо поменять

2018-12-12 11:20 UTC, saint88 commented on homework6/tvProgramProject/src/main/java/pages/MainPage.java
> +    private SelenideElement listView = $("[class='p-channels p-channels_list']");
аналогично выше

2018-12-12 11:20 UTC, saint88 commented on homework6/tvProgramProject/src/main/java/pages/MainPage.java
> +    private SelenideElement gridView = $("[class='p-channels p-channels_grid']");
точно такой же локатор написан выше. Лучше передавать тип отображения через константы enum и сделать один локатор-шаблон

2018-12-12 11:20 UTC, saint88 commented on homework6/tvProgramProject/src/main/java/pages/MainPage.java
> +    public MainPage switchToGridView(){
В чем разница между этим методом и методом выше? Надо сделать один общий метод

2018-12-12 11:20 UTC, saint88 commented on homework6/tvProgramProject/src/main/java/pages/MainPage.java
> +        channelsCollection.forEach(chanel -> chanel.should(Condition.visible));
Не нужно мешать шаг клика и шаг проверки отображения

2018-12-16 17:26 UTC, hexekute commented on homework5/weatherProject/src/main/java/mfti/month/Month.java
> +    private static final String[] months = {"Январь", "Февраль", "Март", "Апрель",
Нужны же месяцы на русском

2018-12-18 06:42 UTC, merged